### ISSUE TITLE
Request headers bug

### ISSUE THREAD

**Issue by Abilay99** [felangel/fresh#72] opened 2022-11-30 11:46 UTC
I can't refresh token because of i use accessToken for API refreshToken for refreshing token but _httpClient interceptors using Fresh. There are changed headers Authorization only for refreshToken. How to solve this problem?

**Comment by felangel** [comment] 2022-12-01 05:37
Can you share some sample code or a reproduction sample? I'm not sure I fully understand the problem you're facing, thanks!

**Comment by Abilay99** [comment] 2022-12-02 10:27
class TranslateApiRequestFailureException implements Exception {
  TranslateApiRequestFailureException([String message = '']){
    _message = message;
  }

  late String _message;

  @override
  String toString() {
    return _message;
  }

}

class TranslateApiClient {
  TranslateApiClient({Dio? httpClient})
      : _httpClient = (httpClient ?? Dio())
    ..options.baseUrl = baseUrl
    ..interceptors.add(_fresh)
    ..interceptors.add(
      LogInterceptor(),
    )
    ..options.followRedirects=false
    ..options.validateStatus=((status) => status != null && status <= 505);

  final Dio _httpClient;

  static final _fresh = Fresh.oAuth2(
    tokenHeader: (token){
      if (token.accessToken == '') {
        return {};
      }
      return {
        'Authorization': '${token.tokenType} ${token.accessToken}',
      };
    },
    tokenStorage: CacheTokenMemory(),
    refreshToken: (token, client) async {
      client.options.headers.addAll(
        {
          'Authorization': '${token?.tokenType} ${token?.refreshToken}',
        },
      );
      try {
        final response = await client.post<dynamic>('/auth/refresh',);

        if(response.statusCode != 201 || response.statusCode != 200){
          throw RevokeTokenException();
        }

        final data = response.data as Map<String, dynamic>;
        final accessToken = data['access_token'].toString();
        final refreshToken = data['refresh_token'].toString();

        return OAuth2Token(
          accessToken: accessToken,
          refreshToken: refreshToken,
        );
      } on DioError catch(err){
        print(err.message);
      }
      return const OAuth2Token(
        accessToken: '',
      );
    },
  );

  Stream<AuthenticationStatus> get authenticationStatus =>
      _fresh.authenticationStatus;

  Future<void> authenticate({
    required String username,
    required String password,
  }) async {
    final response = await _httpClient.post<dynamic>('/auth/login', data: {'user_credentials': username, 'password': password});
    if(response.statusCode != 200){
      throw TranslateApiRequestFailureException(response.data['msg'].toString());
    }
    final data = response.data as Map<String, dynamic>;
    final accessToken = data['access_token'].toString();
    final refreshToken = data['refresh_token'].toString();
    await _fresh.setToken(
       OAuth2Token(
        accessToken: accessToken,
        refreshToken: refreshToken,
      ),
    );
  }

  Future<void> unauthenticate() async {
    final response = await _httpClient.delete<dynamic>('/auth/logout');
    if(response.statusCode != 200){
      throw RevokeTokenException();
    } else{
      await _fresh.setToken(null);
    }
  }

  Future<Translate> translate(String text) async {
    final response = await _httpClient.post<dynamic>('/v1/translate',
        data: Translate(text: text).toJson(),
    );
    if (response.statusCode != 200) {
      throw TranslateApiRequestFailureException(response.data['msg'].toString());
    }

    return Translate.fromJson(response.data as Map<String, dynamic>);
  }

  Future<List<Translate>> translates() async {
    final response = await _httpClient.get<dynamic>(
      '/v1/translate',
    );

    if (response.statusCode != 200) {
      throw TranslateApiRequestFailureException(response.data['msg'].toString());
    }

    return (response.data["results"] as List)
        .map((dynamic translate) =>
            Translate.fromJson(translate as Map<String, dynamic>),)
        .toList();
  }

  Future<Translate> changeTranslate(Translate translate) async {
    final response = await _httpClient.put<dynamic>('/v1/translate',
      data: translate.toJson(),);

    if (response.statusCode != 200) {
      throw TranslateApiRequestFailureException(response.data['msg'].toString());
    }

    return Translate.fromJson(response.data as Map<String, dynamic>);
  }
}

**Comment by Abilay99** [comment] 2022-12-02 10:28
````
class TranslateApiRequestFailureException implements Exception {
  TranslateApiRequestFailureException([String message = '']){
    _message = message;
  }

  late String _message;

  @override
  String toString() {
    return _message;
  }

}

class TranslateApiClient {
  TranslateApiClient({Dio? httpClient})
      : _httpClient = (httpClient ?? Dio())
    ..options.baseUrl = baseUrl
    ..interceptors.add(_fresh)
    ..interceptors.add(
      LogInterceptor(),
    )
    ..options.followRedirects=false
    ..options.validateStatus=((status) => status != null && status <= 505);

  final Dio _httpClient;

  static final _fresh = Fresh.oAuth2(
    tokenHeader: (token){
      if (token.accessToken == '') {
        return {};
      }
      return {
        'Authorization': '${token.tokenType} ${token.accessToken}',
      };
    },
    tokenStorage: CacheTokenMemory(),
    refreshToken: (token, client) async {
      client.options.headers.addAll(
        {
          'Authorization': '${token?.tokenType} ${token?.refreshToken}',
        },
      );
      try {
        final response = await client.post<dynamic>('/auth/refresh',);

        if(response.statusCode != 201 || response.statusCode != 200){
          throw RevokeTokenException();
        }

        final data = response.data as Map<String, dynamic>;
        final accessToken = data['access_token'].toString();
        final refreshToken = data['refresh_token'].toString();

        return OAuth2Token(
          accessToken: accessToken,
          refreshToken: refreshToken,
        );
      } on DioError catch(err){
        print(err.message);
      }
      return const OAuth2Token(
        accessToken: '',
      );
    },
  );

  Stream<AuthenticationStatus> get authenticationStatus =>
      _fresh.authenticationStatus;

  Future<void> authenticate({
    required String username,
    required String password,
  }) async {
    final response = await _httpClient.post<dynamic>('/auth/login', data: {'user_credentials': username, 'password': password});
    if(response.statusCode != 200){
      throw TranslateApiRequestFailureException(response.data['msg'].toString());
    }
    final data = response.data as Map<String, dynamic>;
    final accessToken = data['access_token'].toString();
    final refreshToken = data['refresh_token'].toString();
    await _fresh.setToken(
       OAuth2Token(
        accessToken: accessToken,
        refreshToken: refreshToken,
      ),
    );
  }

  Future<void> unauthenticate() async {
    final response = await _httpClient.delete<dynamic>('/auth/logout');
    if(response.statusCode != 200){
      throw RevokeTokenException();
    } else{
      await _fresh.setToken(null);
    }
  }

  Future<Translate> translate(String text) async {
    final response = await _httpClient.post<dynamic>('/v1/translate',
        data: Translate(text: text).toJson(),
    );
    if (response.statusCode != 200) {
      throw TranslateApiRequestFailureException(response.data['msg'].toString());
    }

    return Translate.fromJson(response.data as Map<String, dynamic>);
  }

  Future<List<Translate>> translates() async {
    final response = await _httpClient.get<dynamic>(
      '/v1/translate',
    );

    if (response.statusCode != 200) {
      throw TranslateApiRequestFailureException(response.data['msg'].toString());
    }

    return (response.data["results"] as List)
        .map((dynamic translate) =>
            Translate.fromJson(translate as Map<String, dynamic>),)
        .toList();
  }

  Future<Translate> changeTranslate(Translate translate) async {
    final response = await _httpClient.put<dynamic>('/v1/translate',
      data: translate.toJson(),);

    if (response.statusCode != 200) {
      throw TranslateApiRequestFailureException(response.data['msg'].toString());
    }

    return Translate.fromJson(response.data as Map<String, dynamic>);
  }
}
````

**Comment by Abilay99** [comment] 2022-12-02 10:31
````
class TranslateApiClient {
  TranslateApiClient({Dio? httpClient})
      : _httpClient = (httpClient ?? Dio())
    ..options.baseUrl = baseUrl
    ..interceptors.add(_fresh)
    ..interceptors.add(
      LogInterceptor(),
    )
    ..options.followRedirects=false
    ..options.validateStatus=((status) => status != null && status <= 505);

  final Dio _httpClient;

  static final _fresh = Fresh.oAuth2(
    tokenHeader: (token){
      if (token.accessToken == '') {
        return {};
      }
      return {
        'Authorization': '${token.tokenType} ${token.accessToken}',
      };
    },
    tokenStorage: CacheTokenMemory(),
    refreshToken: (token, client) async {
      client.options.headers.addAll(
        {
          'Authorization': '${token?.tokenType} ${token?.refreshToken}',
        },
      );
      try {
        final response = await client.post<dynamic>('/auth/refresh',);

        if(response.statusCode != 201 || response.statusCode != 200){
          throw RevokeTokenException();
        }

        final data = response.data as Map<String, dynamic>;
        final accessToken = data['access_token'].toString();
        final refreshToken = data['refresh_token'].toString();

        return OAuth2Token(
          accessToken: accessToken,
          refreshToken: refreshToken,
        );
      } on DioError catch(err){
        print(err.message);
      }
      return const OAuth2Token(
        accessToken: '',
      );
    },
  );
}
````

**Comment by felangel** [comment] 2024-07-20 20:20
Closing for now since this issue is quite old. If this is still an issue with the latest version of the package let me know and I'm happy to take a closer look, thanks!

**Closed by felangel** 2024-07-20 20:20 UTC
Labels: question
