### ISSUE TITLE
What server has to return to make fresh work?

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [felangel/fresh#51] opened 2021-08-20 06:46 UTC
Hi, I have a situation when i was sure that this peace is working. However today i have realized that it is not. I checked your example and implement things similarly. However I am not sure what server has to return to make it work. Now from server I am returning pure gql error (when calling via postman)

```
{
    "errors": [
        {
            "message": "Context creation failed: Authentication token is invalid, please log in",
            "extensions": {
                "code": "UNAUTHENTICATED",
                "exception": {
                    "stacktrace": [
                        "AuthenticationError: Context creation failed: Authentication token is invalid, please log in",
                        "    at ApolloServer.context (D:\\SenioAssist\\senioassit-api\\src\\main.ts:71:23)",
                        "    at runMicrotasks (<anonymous>)",
                        "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
                    ]
                }
            }
        }
    ]
}
```

And i am sure that previously this error was caught by fresh plugin however now it is not. And i see this error in console 
```
Caught error: OperationException(linkException: ServerException(originalException: null, parsedResponse: Response(data: null, errors: [GraphQLError(message: Context creation failed: Authentication token is invalid, please log in, locations: null, path: null, extensions: {code: UNAUTHENTICATED, exception: {stacktrace: [AuthenticationError: Context creation failed: Authentication token is invalid, please log in,     at ApolloServer.context (D:\SenioAssist\senioassit-api\src\main.ts:71:23),     at runMicrotasks (<anonymous>),     at processTicksAndRejections (internal/process/task_queues.js:93:5)]}})], context: Context({ResponseExtensions: Instance of 'ResponseExtensions'}))), graphqlErrors: [])
```

I am not sure why server error is not wrapped into linkException rather than graphqlErrors.

Maybe I am returning it incorrect from server? maybe it is because when I am throwing AuthenticationError from Apollo server it gives 400 (bad request) instead of 200 along with error mentioned above?

**Comment by vytautas-pranskunas-** [comment] 2021-08-20 08:13
After some testing I see that problem is 400 status code.
Just do not understand how your code works because if i thorw AuthenticationError in context create from ApolloServer it returns 400.

https://github.com/apollographql/apollo-server/issues/1709

**Comment by felangel** [comment] 2021-08-20 13:54
Hi @vytautas-pranskunas- 👋
Thanks for opening an issue!

Are you able to provide a link to a minimal reproduction sample? I’m happy to take a closer look at the specific issue you’re encountering 👍

**Comment by vytautas-pranskunas-** [comment] 2021-08-20 14:06
I can give you code snippets:

```
const apolloServer = new ApolloServer({
        schema,
        context: async ({ req, connection }: { req: any; connection: any }) => {
            if (connection) {
                return connection.context;
            }
            throw new AuthenticationError('Authentication token is invalid, please log in');
            return {  } ;
        },
       
    });

```

rest you can take from https://www.apollographql.com/docs/apollo-server/getting-started/

**Comment by felangel** [comment] 2024-07-20 20:17
Closing this for now since this is quite old but if this is still an issue please let me know and I'm happy to take a closer look.

**Closed by felangel** 2024-07-20 20:17 UTC
