### ISSUE TITLE
How to test fresh_dio with a Mock HttpClientAdapter?

### ISSUE THREAD

**Issue by sidroniolima** [felangel/fresh#94] opened 2023-11-07 14:13 UTC
Thanks for the package!

I'm trying to test an API that uses the fresh_dio passing a HttpClientAdapter Mock as a dio.httpClientAdapter.

I can make some tests pass. Like this one:

`final httpPostResponse = ResponseBody.fromString(
          responseData,
          200,
          headers: {
            Headers.contentTypeHeader: [Headers.jsonContentType],
          },
        );

        when(
          () => mockDioAdapter.fetch(
            any(
              that: isA<RequestOptions>().having(
                (options) => options.method,
                'POST method',
                equals('POST'),
              ),
            ),
            any(),
            any(),
          ),
        ).thenAnswer((_) async => httpPostResponse);

        await meuEspacoApiClient.authenticate(
          username: 'username',
          password: 'password',
        );

        expect(
          meuEspacoApiClient.authenticationStatus,
          emitsAnyOf([AuthenticationStatus.authenticated]),
        );

        verify(
          () => mockDioAdapter.fetch(
            any(
              that: isA<RequestOptions>()
                  .having(
                    (options) => options.method,
                    'POST method',
                    equals('POST'),
                  )
                  .having(
                    (options) => options.baseUrl,
                    'Base URL',
                    equals('http://localhost:8080'),
                  ),
            ),
            any(),
            any(),
          ),
        ).called(1);`

But when I return a response with a status code equals to 401, then a refresh function is not called and the following DioException occurs:

DioException [bad response]: The request returned an invalid status code of 401.

If I handle the exception it not trigger the refresh token even.

I'm using this package wrong or missing something? 

Please, help me.

**Comment by felangel** [comment] 2024-07-20 20:21
Closing for now since this is quite old but if you're still having trouble please share a link to a complete, minimal reproduction sample and I'm happy to take a closer look, thanks!

**Closed by felangel** 2024-07-20 20:21 UTC
