### ISSUE TITLE
Remove limit to Web only with `dart:html`

### ISSUE THREAD

**Issue by magillus** [felangel/fresh#3] opened 2020-04-27 13:10 UTC
![image](https://user-images.githubusercontent.com/729803/80375816-82bdc680-885e-11ea-8635-d20a2601f00d.png)

**Comment by magillus** [comment] 2020-04-27 13:11
or even: `forbidden = 403;`

**Comment by felangel** [comment] 2020-04-27 13:12
Hey @magillus thanks for opening an issue!
This is a duplicate of #2 and is fixed on the release branch. I’ll have it merged shortly 👍

**Closed by felangel** 2020-04-27 13:12 UTC
